version: '3.8'
services:
  mysql:
    image: mysql:8.0.35
    env_file:
      - ./env/mysql.env
    volumes:
      - /Users/repoleved/Desktop/docker/recon-mysql:/var/lib/mysql
    ports:
      - 3306:3306