version: '3.8'
services:
  mysql:
    image: mysql:8.0.35
    env_file:
      - ./env/mysql.env
    volumes:
      - /Users/repoleved/Desktop/docker/recon-mysql:/var/lib/mysql
  eureka:
    build: 
      context: ./recon-discovery-service
      dockerfile: Dockerfile
    ports:
      - 8761:8761
  recon-core:
    build:
      context: ./reconV2
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - eureka
      - mysql
  recon-reports:
    build:
      context: ./recon-report-service
      dockerfile: Dockerfile
    ports:
      - 4001:4001
    depends_on:
      - eureka
      - mysql
  recon-email:
    build:
      context: ./recon-email-service
      dockerfile: Dockerfile
    ports:
      - 4002:4002
    depends_on:
      - eureka
      - mysql

