version: '3.8'
services:
  mysql:
    image: mysql:8.0.35
    env_file:
      - ./env/mysql.env
    volumes:
      - /Users/repoleved/Desktop/docker/recon-mysql:/var/lib/mysql
  eureka:
    build: 
      context: ./recon-discovery-service
      dockerfile: Dockerfile
    env_file:
      - env/recon-eureka.env
    ports:
      - $RECON_EUREKA_HOST_PORT:$RECON_EUREKA_APP_PORT
  recon-core:
    build:
      context: ./reconV2
      dockerfile: Dockerfile
    env_file:
      - env/recon-core.env
    ports:
      - $RECON_CORE_HOST_PORT:$RECON_CORE_APP_PORT
    depends_on:
      - eureka
      - mysql
  recon-reports:
    build:
      context: ./recon-report-service
      dockerfile: Dockerfile
    env_file:
      - ./env/recon-report.env
    ports:
      - $RECON_REPORT_HOST_PORT:$RECON_REPORT_APP_PORT
    depends_on:
      - eureka
      - mysql
  recon-email:
    build:
      context: ./recon-email-service
      dockerfile: Dockerfile
    env_file:
      - env/recon-email.env
    ports:
      - $RECON_EMAIL_HOST_PORT:$RECON_EMAIL_APP_PORT
    depends_on:
      - eureka
      - mysql

