spring.application.name=recon
server.port=${RECON_GATEWAY:8080}

eureka.client.service-url.defaultZone=http://${EUREKA_SERVICE_NAME:localhost}:8761/eureka

# Gateway route matching, predicates, filters
#logging.level.org.springframework.cloud.gateway=DEBUG

# WebFlux request handling
#logging.level.org.springframework.web.reactive=DEBUG
#logging.level.org.springframework.http.server.reactive=DEBUG

# Reactor Netty client/server behavior
#logging.level.reactor.netty=DEBUG

# Show route actuator endpoint
management.endpoint.gateway.enabled=true
management.endpoints.web.exposure.include=health,info,gateway

# Circuit breaker settings - for Recon Core learning purposes. set lower so I can trigger circuit breaker manually to open state and get fail fast rejections
resilience4j.circuitbreaker.instances.recon-core-ms.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.recon-core-ms.sliding-window-size=5
resilience4j.circuitbreaker.instances.recon-core-ms.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.recon-core-ms.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.recon-core-ms.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.recon-core-ms.permitted-number-of-calls-in-half-open-state=2

resilience4j.timelimiter.instances.recon-core-ms.timeout-duration=10s

# Gateway timeout
# NOTE: hiearchy -> TimeLImter (circuit breaker) [wraps call] -> response timeout [inside TimeLimiter and failure counts toward TimeLimiter fail count]
# Resilience4j TimeLimiter: 2s (circuit breaker timeout) will effectively beat out connection timeout
# TimeLimiter = "How long will I allow the whole protected call to run?"
# Gateway global response timeout: 3s
# connect-timeout = "How long will I wait to establish a network connection?"
# Gateway route response timeout: 10s
# response-timeout = "How long will Gateway HTTP client wait for backend response?"
spring.cloud.gateway.httpclient.connect-timeout: ${RECON_GATEWAY_CONNECTION_TIMEOUT:1000}
spring.cloud.gateway.httpclient.response-timeout: ${RECON_GATEWAY_SERVICE_RESPONSE_TIMEOUT:3s}

