server:
  port: 4001
  
eureka:
  client:
    register-with-eureka: false
    fetch-registry:  false
    serviceUrl:
      defaultZone: http://localhost:4001/eureka/
      
logging:
  file:
    path: /
    name: log.txt
  level: 
    '[com.recon.discoveryServer': debug
    root: INFO

#Setup Actuator port and exposed all actuator endpoints
#managment:
# endpoints:
#   web:
#     exposure:
#       include: "*"
