name: CI Pipeline

run-name: Continous Integration - Pull Image, Build Maven and Verify Java services

on:
  workflow_dispatch:
  push:
    # feature/* matches feature/feature-name (one slash)
    # feature/** matches feature/feature-name/123 (multiple slashes)
    branches: [ feature/**, dockerized ]
  pull_request:
    branches: [ dockerized ]

jobs:
  build:
    name: Build and Verify Java services
    runs-on: ubuntu-latest

    strategy:
      # Don't fail the entire build if one service fails'
      fail-fast: false
      matrix:
        service:
          - recon-discovery-service
          - reconV2
          - recon-report-service
          - recon-email-service
          - recon-gateway

    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Run a one-line script
        run: echo "Starting automated tests..."

      - name: Set up Java 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
          cache-dependency-path: ${{ matrix.service }}/pom.xml

      - name: Build ${{ matrix.service }}
        working-directory: ${{ matrix.service }}
        run: mvn -B clean verify

